/**
 * Generate the embedded 5 Draw strategy data file from training output.
 *
 * Reads the latest five-draw-strategy-*.json and generates
 * shared/src/cfr/fiveDrawStrategyData.ts.
 */

import * as fs from 'node:fs';
import * as path from 'node:path';

const STRATEGIES_DIR = path.resolve(import.meta.dirname, '../strategies');
const OUTPUT_FILE = path.resolve(import.meta.dirname, '../../shared/src/cfr/fiveDrawStrategyData.ts');

// Find the latest 5 Draw strategy file
const files = fs.readdirSync(STRATEGIES_DIR)
  .filter(f => f.startsWith('five-draw-strategy-') && f.endsWith('.json'))
  .sort((a, b) => {
    const numA = parseInt(a.match(/five-draw-strategy-(\d+)/)?.[1] ?? '0', 10);
    const numB = parseInt(b.match(/five-draw-strategy-(\d+)/)?.[1] ?? '0', 10);
    return numA - numB;
  });

const latestFile = files[files.length - 1];
if (!latestFile) {
  console.error('No five-draw-strategy-*.json files found in training/strategies/');
  console.error('Run training first: npm run train-five-draw -w training');
  process.exit(1);
}

const filepath = path.join(STRATEGIES_DIR, latestFile);
const data = JSON.parse(fs.readFileSync(filepath, 'utf-8'));
const strategy = data.strategy as Record<string, Record<string, number>>;
const infoSetCount = Object.keys(strategy).length;

console.log(`  Loading: ${latestFile} (${infoSetCount} info sets)`);

const output = `/**
 * Embedded 5 Draw CFR strategy data — auto-generated by generateFiveDrawStrategyData.ts.
 * Do not edit manually.
 *
 * Info sets: ${infoSetCount}
 * Iterations: ${data.iterations}
 */

/** Action probability distribution for one info set. */
export interface FiveDrawStrategyEntry {
  [action: string]: number;
}

/** Pre-computed 5 Draw strategy lookup: info set key → action probabilities. */
export const FIVE_DRAW_STRATEGY_DATA: Readonly<Record<string, FiveDrawStrategyEntry>> = ${JSON.stringify(strategy)} as Record<string, FiveDrawStrategyEntry>;
`;

fs.writeFileSync(OUTPUT_FILE, output, 'utf-8');
console.log(`\nGenerated ${OUTPUT_FILE}`);
console.log(`  Info sets: ${infoSetCount}`);
console.log(`  File size: ${(Buffer.byteLength(output) / 1024).toFixed(1)} KB`);
